kind: Service
apiVersion: v1
metadata:
  name: greeting-processor
  labels:
    app: greeting-processor
spec:
  selector:
    app: greeting-processor
  ports:
    - port: 8080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: greeting-processor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-processor
        version: v1
    spec:
      containers:
      - name: greeting-processor
        env:
        - name: GREETING
          value: Hi
        image: docker.sebastian-daschner.com/greeting-processor:2
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: greeting-processor
spec:
  rules:
    - host: kubernetes.local
      http:
        paths:
        - path: /greeting-processor
          backend:
            serviceName: greeting-processor
            servicePort: 8080
---